"""
Django settings for Saas project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0&uz-q%pyi#7c_2t5uo1hzrem(20l6*#pm25r97_-79fbgni#o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =True


ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01',
    'web'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'web.middlewares.auth.AuthMiddlewares'  # 中间件应用
]

ROOT_URLCONF = 'Saas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'project': 'web.templatetags.project'
            },
        },
    },
]

WSGI_APPLICATION = 'Saas.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'SaaS',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
#datetime.datetime.now() / datetime.datetime.utcnow() -> utc时间
# TIME_ZONE = 'UTC'
#datetime.datetime.now()-->东八区时间 / datetime.datetime.utcnow() -> utc时间
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True

USE_L10N = True
#影响自动生成数据库时间字段：
# USE_TZ = True　，创建ＵＴＣ时间写入数据库
# USE_TZ = Ｆａｌｓｅ　，根据TIME_ZONE设置的时区进行创建时间并写入数据库

USE_TZ =False
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
# 自己的短信模板
# 腾讯云短信应用的 app_id
TENCENT_SMS_APP_ID = 6666666666

# 腾讯云短信应用的 app_key
# TENCENT_SMS_APP_KEY = "6666666666666666666666"

# 腾讯云短信签名内容
TENCENT_SMS_SIGN = "Python之路"

TENCENT_SMS_TEMPLATE = {
    'register': 845947,
    'login': 845950
}

#腾讯云对象储存COS的id和key
TENCENT_COS_ID = 'COS的secret_id'
TENCENT_COS_KEY = 'COS的secret_key'


# #############登录白名单:无需登录就能访问的页面 #########################

WHITE_REGEX_URL_LIST = [
    '/register/',
    '/send/sms/',
    '/login/',
    '/image_code/',
    '',
    '/login/sms/',
    '/price/',

]

try:  # 异常捕获 如果有 local_settings加载,没有pass
    from .local_settings import *

except ImportError:
    pass
